server:
  port: 8081
spring:
  application:
    name: hr-worker
  datasource:
    password: ''
    url: jdbc:h2:mem:lucasdb
    username: sa
  h2:
    console:
      enabled: true
      path: /h2-console
