spring:
  application:
    name: hr-worker
  datasource:
    password: ''
    url: jdbc:h2:mem:lucasdb
    username: sa
  h2:
    console:
      enabled: true
      path: /h2-console
      
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${random.value}
      
server:
  port: ${PORT:0}


      
