spring:
  application:
    name: hr-worker
      
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${random.value}
      
server:
  port: ${PORT:0}


      
